# Generated by Django 3.2.22 on 2023-10-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='ttulo',
            new_name='titulo',
        ),
    ]
