# Generated by Django 3.2.22 on 2023-10-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0002_rename_ttulo_tarea_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='usuario_asignado',
            new_name='usuarios_asignados',
        ),
    ]
