# Generated by Django 3.2.22 on 2023-10-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0003_rename_usuario_asignado_tarea_usuarios_asignados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='etiqueta',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_creador', to='ejercicio.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to='ejercicio.tarea'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='tarea',
            field=models.ManyToManyField(related_name='etiquetas_tareas', to='ejercicio.Tarea'),
        ),
    ]
