# Generated by Django 3.2.22 on 2023-10-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0004_auto_20231028_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
    ]
